# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

[workspace]
resolver = "3"
members = [
    "crates/kcsdi-core",
    "crates/kcsdi-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Huang Rui <vowstar@gmail.com>"]
license = "MIT"
repository = "https://github.com/vowstar/kcsdi-rs"

[profile.release]
opt-level = 2

[profile.dev.package."*"]
opt-level = 2
